/* Generated by Phoenix Tuner X */
package frc.robot.elevator;

import static edu.wpi.first.units.Units.*;

import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.DutyCycleOut;
import com.ctre.phoenix6.controls.Follower;
import com.ctre.phoenix6.controls.MotionMagicVoltage;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.ForwardLimitSourceValue;
import com.ctre.phoenix6.signals.ForwardLimitTypeValue;
import com.ctre.phoenix6.signals.GravityTypeValue;
import com.ctre.phoenix6.signals.MotorAlignmentValue;
import com.ctre.phoenix6.signals.NeutralModeValue;
import com.ctre.phoenix6.signals.ReverseLimitSourceValue;
import com.ctre.phoenix6.signals.ReverseLimitTypeValue;
import com.ctre.phoenix6.sim.ChassisReference;
import com.ctre.phoenix6.sim.TalonFXSimState;

import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.units.measure.*;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.simulation.ElevatorSim;
import edu.wpi.first.wpilibj.smartdashboard.Mechanism2d;
import edu.wpi.first.wpilibj.smartdashboard.MechanismLigament2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import frc.robot.elevator.ElevatorConstants.Setpoint;

public class ElevatorSubsystem extends SubsystemBase {
    /** Position setpoints for the elevator. */

    private static final int kNumConfigAttempts = 2;
    public static ElevatorConfigs m_ElevatorConfigs = new ElevatorConfigs();
  
    /* leader and follower motors */
    private final CANBus kCANBus = new CANBus("rio");
    private final TalonFX motor_id_1 = new TalonFX(ElevatorConstants.motorOneId, kCANBus);
    private final TalonFX motor_id_2 = new TalonFX(ElevatorConstants.motorTwoId, kCANBus);

    /* device status signals */
    private final StatusSignal<Angle> motor_id_1Position = motor_id_1.getPosition(false);   
    private final StatusSignal<AngularVelocity> motor_id_1Velocity = motor_id_1.getVelocity(false);
    private final StatusSignal<Current> motor_id_1TorqueCurrent = motor_id_1.getTorqueCurrent(false);

    /* controls used by the leader motors */
    private final MotionMagicVoltage setpointRequest = new MotionMagicVoltage(0);
    private final DutyCycleOut manualRequest = new DutyCycleOut(-1);
    private final DutyCycleOut calibrationRequest = new DutyCycleOut(-0.1)
        .withIgnoreHardwareLimits(true)
        .withIgnoreSoftwareLimits(true);

    /** Trigger to detect when the elevator drives into a hard stop. */
    public final Trigger isHardStop = new Trigger(() -> {
        return motor_id_1Velocity.getValue().abs(RotationsPerSecond) < 1 &&
            motor_id_1TorqueCurrent.getValue().abs(Amps) > 10;
    }).debounce(0.1);

    /* simulation */
    private final ElevatorSim elevatorSim_motor_id_1 = new ElevatorSim(
        DCMotor.getKrakenX60Foc(2),
        ElevatorConstants.kGearRatio, 5, ElevatorConstants.kDrumRadius.in(Meters),
        0.0, ElevatorConstants.kMaxHeight.in(Meters), true, 0.0
    );

    private static final double kSimLoopPeriod = 0.002; // 2 ms
    private Notifier simNotifier = null;
    private double lastSimTime = 0.0;

    /* Mechanism2d visualization of the elevator */
    private final Mechanism2d mech2d = new Mechanism2d(1, ElevatorConstants.kMaxHeight.in(Meters));
    private final MechanismLigament2d motor_id_1Mech2d = mech2d.getRoot("motor_id_1 Root", 0.500, 0)
        .append(new MechanismLigament2d("motor_id_1", elevatorSim_motor_id_1.getPositionMeters(), 90));

    public ElevatorSubsystem() {
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = motor_id_1.getConfigurator().apply(m_ElevatorConfigs.motor_id_1Configs);
            if (status.isOK()) break;
        }
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = motor_id_2.getConfigurator().apply(m_ElevatorConfigs.motor_id_2Configs);
            if (status.isOK()) break;
        }

        motor_id_2.setControl(
            new Follower(motor_id_1.getDeviceID(), MotorAlignmentValue.Opposed)
        );

        /* set the default command to neutral output */
        setDefaultCommand(manualDrive(() -> 0.0));
        /* alternatively, the default command can hold position */
        // setDefaultCommand(holdPosition());

        SmartDashboard.putData("Elevator", mech2d);

        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * @return The Position of the elevator
     */
    public Angle getPosition() {
        return motor_id_1Position.getValue();
    }

    /**
     * @return The Velocity of the elevator
     */
    public AngularVelocity getVelocity() {
        return motor_id_1Velocity.getValue();
    }

    /**
     * @return The TorqueCurrent of the elevator
     */
    public Current getTorqueCurrent() {
        return motor_id_1TorqueCurrent.getValue();
    }

    /**
     * Holds the elevator at the current position using PID.
     *
     * @return Command to run
     */
    public Command holdPosition() {
        return runOnce(() ->
            setpointRequest.withPosition(motor_id_1Position.getValue())
        ).andThen(run(() -> {
            motor_id_1.setControl(setpointRequest);
        }));
    }

    /**
     * Drives the elevator to the provided position setpoint.
     *
     * @param setpoint Function returning the setpoint to apply
     * @return Command to run
     */
    public Command goToSetpoint(Supplier<Setpoint> setpoint) {
        return run(() -> {
            SmartDashboard.putNumber("target", setpoint.get().target.magnitude());
            setpointRequest.withPosition(setpoint.get().target);
            motor_id_1.setControl(setpointRequest);
        });
    }

    /**
     * Manually drives the elevator with the provided duty cycle output.
     *
     * @param manualOutput Function returning the duty cycle to apply
     * @return Command to run
     */
    public Command manualDrive(DoubleSupplier manualOutput) {
        return run(() -> {
            manualRequest.withOutput(manualOutput.getAsDouble());
            motor_id_1.setControl(manualRequest);
        });
    }

    /**
     * Recalibrates the elevator zero point. This slowly drives the elevator
     * down until we see a drop in velocity and a spike in stator current,
     * indicating that we've hit a hard stop.
     *
     * @return Command to run
     */
    public Command calibrateZero() {
        return run(() -> {
            motor_id_1.setControl(calibrationRequest);
        })
        .until(isHardStop)
        .andThen(
            manualDrive(() -> 0.0).withTimeout(0.25)
                .finallyDo(() -> {
                    motor_id_1.setPosition(Rotations.of(0));
                    motor_id_2.setPosition(Rotations.of(0));
                })
        );
    }

    @Override
    public void periodic() {
        SmartDashboard.putNumber("current", getPosition().magnitude());

        /* refresh all status signals */
        BaseStatusSignal.refreshAll(
            motor_id_1Position,
            motor_id_1Velocity,
            motor_id_1TorqueCurrent
        );

        motor_id_1Mech2d.setLength(
            motor_id_1Position.getValueAsDouble() * ElevatorConstants.kDrumRadius.in(Meters) * 2 * Math.PI
        );
    }

    private void startSimThread() {
        motor_id_1.getSimState().Orientation = ChassisReference.Clockwise_Positive;
        motor_id_1.getSimState().setMotorType(TalonFXSimState.MotorType.KrakenX60);
        motor_id_2.getSimState().Orientation = ChassisReference.Clockwise_Positive;
        motor_id_2.getSimState().setMotorType(TalonFXSimState.MotorType.KrakenX60);

        lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        simNotifier = new Notifier(() -> {
            /* Calculate the time delta */
            final double currentTime = Utils.getCurrentTimeSeconds();
            final double deltaTime = currentTime - lastSimTime;
            lastSimTime = currentTime;

            final var motor_id_1Sim = motor_id_1.getSimState();
            final var motor_id_2Sim = motor_id_2.getSimState();

            /* First set the supply voltage of all the devices */
            motor_id_1Sim.setSupplyVoltage(RobotController.getBatteryVoltage());
            motor_id_2Sim.setSupplyVoltage(RobotController.getBatteryVoltage());

            /* Then calculate the new position and velocity of the simulated elevator */
            elevatorSim_motor_id_1.setInputVoltage(motor_id_1Sim.getMotorVoltage());
            elevatorSim_motor_id_1.update(deltaTime);

            /* Apply the new rotor position and velocity to the motors (before gear ratio) */
            motor_id_1Sim.setRawRotorPosition(
                Radians.of(elevatorSim_motor_id_1.getPositionMeters() / ElevatorConstants.kDrumRadius.in(Meters) *ElevatorConstants.kGearRatio)
            );
            motor_id_1Sim.setRotorVelocity(
                RadiansPerSecond.of(elevatorSim_motor_id_1.getVelocityMetersPerSecond() / ElevatorConstants.kDrumRadius.in(Meters) * ElevatorConstants.kGearRatio)
            );
            motor_id_2Sim.setRawRotorPosition(
                Radians.of(elevatorSim_motor_id_1.getPositionMeters() / ElevatorConstants.kDrumRadius.in(Meters) * ElevatorConstants.kGearRatio)
            );
            motor_id_2Sim.setRotorVelocity(
                RadiansPerSecond.of(elevatorSim_motor_id_1.getVelocityMetersPerSecond() / ElevatorConstants.kDrumRadius.in(Meters) * ElevatorConstants.kGearRatio)
            );
        });
        simNotifier.startPeriodic(kSimLoopPeriod);
    }
}